# wrangler.toml
name = 'tes'
main = "dist/worker.js"
compatibility_date = "2024-09-23"

[build]
command = "npm run build"

# Development configuration
[vars]
UUID = "08dad8a6-8a6c-4424-9d63-62f3a9bf7f4f,49d598ee-4dfc-4001-95ca-99a5b6002e3c"
PROXY_IP = "172.66.45.9:443,104.18.128.25:443,162.159.136.94:443"
